version: '3.3'

services: 

    web:
        container_name: tastetify
        build: .
        ports: 
            - 8000:80
        volumes: 
            - ./:/var/www/html
        networks: 
            - app

    postgre:
        container_name: postgres
        image: postgres:13-alpine    
        ports: 
            - 5432:5432
        environment: 
            POSTGRES_PASSWORD: root
            POSTGRES_USER: root
            POSTGRES_DB: tastetify

        networks: 
            - app

networks: 
    app:
        driver: bridge
        